# Change these first
owner: ManfredRichthofen # Your GitHub organization or username, where this repository lives
repo: Uptime-Monitor # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Home Page
    url: https://requests.jfapp.xyz
  - name: Jellyfin
    url: https://jfapp.xyz
    headers:
      - "User-Agent: test uptime"
  - name: Movie Requests
    url: https://requests.jfapp.xyz
  - name: Movie Downloader
    url: https://dl.jfapp.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jfapp.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: Live status page for all Jellyfin services.
  introMessage:
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
